### PR TITLE
snapd: update to 2.56.2, cleanup configuration, drop unneeded files

### PR DESCRIPTION
**Pull request by bboozzoo**
Update to 2.56.2

Based on #6. Verified manually.

### CODE REVIEW

**Comment by rpjday** [comment]
I just tried 2.56.2, and got an error of the form:

| fork/exec
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/build-tmp/go-build3643160550/b001/exe/info:
no such file or directory
| WARNING:
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/temp/run.do_configure.2548506:173
exit 1 from 'do_configure'

Any idea what that is about? I'll try it again just to make sure it's
reproducible.

rday

**Comment by bboozzoo** [comment]
Can you add a bit more of the log? The upstream code now invokes `go run` in mkversion.sh to generate some data. This should be fixed with https://github.com/snapcore/meta-snapd/pull/7/files#diff-89fe60ac7e0bc1ae9dddc3ec25a13cd633ab5eb81e2894750572b7028ce428c5R76-R77 which sets `GOARCH=${GOHOSTARCH}` when calling mkversion. Builds fine here and in our internal system.

**Review by om26er — APPROVED** [review]
looks good to me. We have the same recipes working in our Yocto build as well

**Comment by rpjday** [comment]
The tail end of my build simply migrating from 2.55.5 to 2.56.2:

| HASH[link github.com/snapcore/snapd/asserts/info]: "packagefile
image/internal/imageutil=jWuGHdNQMFEkkw-tpsmW\n"
| HASH[link github.com/snapcore/snapd/asserts/info]: "packagefile
crypto/ed25519/internal/edwards25519/field=oXX5ZedlvcIe4QP8mUeM\n"
| HASH[link github.com/snapcore/snapd/asserts/info]: "packagefile
crypto/elliptic/internal/fiat=AZi0ePrbJuWL6y7WK1Ew\n"
| HASH[link github.com/snapcore/snapd/asserts/info]: "packagefile
internal/intern=n7vNRfFN9GEjkl2y_pAx\n"
| HASH[link github.com/snapcore/snapd/asserts/info]:
46b3d422814de36d65ac50c90922360e3bc914107c898540c75ec4bd433916bf
| HASH subkey
5506c7084dfddc36bd32885b32d1dd4b610c566684eae68b5c68b6a4fafe1f16
"link-stdout" =
b0268d3e1ff8198624d7210565f1aed8da3761fb05e0dc995e76dbb2c0b19435
| fork/exec
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/build-tmp/go-build919158439/b001/exe/info:
no such file or directory
| WARNING:
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/temp/run.do_configure.2652666:173
exit 1 from 'do_configure'
| WARNING: Backtrace (BB generated script):
| #1: do_configure,
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/temp/run.do_configure.2652666,
line 173
| #2: main,
/home/rpjday/oe/builds/alt_snapd/tmp-glibc/work/core2-64-oe-linux/snapd/2.56.2-r0/temp/run.do_configure.2652666,
line 321
ERROR: Task
(/home/rpjday/oe/dist/layers/meta-snapd/recipes-support/snapd/snapd_2.56.2.bb:do_configure)
failed with exit code '1'
NOTE: Tasks Summary: Attempted 2599 tasks of which 2594 didn't need to be
rerun and 1 failed.

Summary: 1 task failed:

/home/rpjday/oe/dist/layers/meta-snapd/recipes-support/snapd/snapd_2.56.2.bb:
do_configure
Summary: There was 1 ERROR message, returning a non-zero exit code.

**Comment by rpjday** [comment]
Actually, ignore my report -- if this PR works for others, merge it, and
I'll rebase my local changes on top of that.

rday

**Pull request merged**
